# Generated by Django 3.2.18 on 2023-04-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_sms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
